spring:
  application:
    name: uaa
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-oauth2-demo
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


server:
  port: 8000
  tomcat:
    remote-ip-header: x‐forwarded‐for
    protocol-header: x‐forwarded‐proto
  use-forward-headers: true
  servlet:
    context-path: /uaa





logging:
  level:
    root: info

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - text/html
        - appliication/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true
