spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
server:
  port: 8004

zuul:
  retryable: true
  ignored-services: "*"
  add-host-header: true
  sensitive-headers: "*"
  routes:
    uaa:
      stripPrefix: false
      path: /uaa/**
    order:
      stripPrefix: false
      path: /order/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - text/html
        - appliication/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true
