server:
  port: 8001
  tomcat:
    remote-ip-header: x‐forwarded‐for
    protocol-header: x‐forwarded‐proto
  use-forward-headers: true
  servlet:
    context-path: /sso1


spring:
  application:
    name: sso1
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-oauth2-demo
    username: root
    password: luyanan
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
  instance:
    prefer-ip-address: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .ftl
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
security:
  oauth2:
    client:
      clientId: test_client
      clientSecret: test_client
      accessTokenUri: http://localhost:8000/auth/oauth/token
      userAuthorizationUri: http://localhost:8000/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8000/auth/user
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env


feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - text/html
        - appliication/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true


