spring:
  application:
    name: session
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-oauth2-demo?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: root
    password: rootroot



